version: '3.8'

networks:
  poc:
    driver: bridge

services:
  api:
    networks:
      - poc
    container_name: poc-nest
    build:
      context: .
    image: poc-nest
    env_file:
      - .env
    volumes:
      - ./:/code
      - ./node_modules:/code/node_modules
    ports:
      - ${EXPOSED_PORT:-4000}:${PORT:-3000}
