name: Ensure Code Quality
on: pull_request
jobs:
  build:
    name: Run linter and tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [22]
    steps:
      - name: Checkout Github repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run build --if-present
      - name: Run unit tests
        run: npm run test


